# Generated by Django 4.1.7 on 2023-04-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_text_todoitem__text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='_text',
            new_name='text',
        ),
    ]
